# Generated by Django 4.2.6 on 2023-10-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_cuttingmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuttingMethod',
        ),
    ]
